version: "3"

services:

  api:
    image: line-check-api
    environment:
      DB_HOST: database
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - subnet

  database:
    image: postgres:12
    container_name: database
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: linecheck
    ports:
     - "5442:5432"
    networks:
      - subnet
    volumes:
      - database:/var/lib/postgresql/data

networks:
  subnet:

volumes:
  database: